# Generated by Django 4.1.3 on 2023-09-25 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsPortals', '0002_alter_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscripers',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
