# Generated by Django 4.2.3 on 2023-09-26 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsPortals', '0003_category_subscripers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscripers',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
