# Generated by Django 4.2.4 on 2023-09-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='heading',
            field=models.CharField(default='Sport', max_length=50, unique=True),
        ),
    ]
